cookietemple_version: '1.4.1 # <<COOKIETEMPLE_NO_BUMP>>'
domain: cli
language: python
project_slug: oktoberfest
project_slug_no_hyphen: oktoberfest
template_version: '2.1.1 # <<COOKIETEMPLE_NO_BUMP>>'
template_handle: cli-python
github_username: wilhelm-lab
creator_github_username: victorgiurcoiu
is_github_repo: true
is_repo_private: false
is_github_orga: true
github_orga: wilhelm-lab
full_name: Victor Giurcoiu
email: victor.giurcoiu@tum.de
project_name: oktoberfest
project_short_description: Public repo oktoberfest
version: 0.7.0
license: MIT
