comment:
    layout: "reach,diff,flags,tree"
    behavior: default
    require_changes: false
    require_base: false
    require_head: false
coverage:
    status:
        project:
            default:
                target: auto
                informational: true
        patch:
            default:
                target: auto
                informational: true
