name: cookietemple lint

on: [push]

jobs:
    run:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              name: Check out source-code repository

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.9

            - name: Install cookietemple
              run: pip install cookietemple==1.4.1

            - name: Run cookietemple lint
              run: cookietemple lint .
